feat: Edit and delete plugins
gliff-ai/manage pull request #268
Opened 2022-02-03 15:25 UTC by SilviaZeta

## Description
Add edit and delete functionality for plugins (see #220).

closes #220
relies on https://github.com/gliff-ai/manage/pull/252

Note: requires icons from a newer version of `@gliff-ai/style`.

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

2022-02-03 18:15 UTC, joshuajames-smith requested changes
Looking like a good amount is done! Just a few things I'd like to add and change unless this issue needs closed ASAP?

- [ ] `Edit` icon is currently 'x' but can you swap this with the 'cog' icon?
- [ ] The `beta` icon should be in the top green bar to indicate status of the feature 
- [ ] The `?` icon should also be in the top green bar and if click redirect to plugins page in the documentation [pending @philhallbio ?]
- [ ] Could you move the `Confirm` button to the bottom-right instead of bottom-left?
- [ ] With the delete warning dialogue, I believe the purple is off? I record the colour as # A67EF6 or R:166 G:126 B:246 but the gliff.ai branding colour for purple is #AE79FF or R:174 G:121 B:255
- [x] Could the `Warning` icon be a bit larger on the dialogue?
- [ ] Also could the button sit in the corners of the dialogue and align to the 'heading' or 'x'?

<img width="400" alt="Screenshot 2022-02-03 at 18 11 59" src="https://user-images.githubusercontent.com/83074763/152403304-63a17eb2-8ae3-4a2e-a2ba-3d15e5cd16cc.png">
<img width="400" alt="Screenshot 2022-02-03 at 18 15 24" src="https://user-images.githubusercontent.com/83074763/152403781-52b59ad4-dbd8-495a-97f4-3e3c19d63d9a.png">


Last question, is the warning dialogue font just a smidge too small? Do we have a dialogue implemented elsewhere yet? Maybe just up a couple px if we think we needs it!

Otherwise that might be it for this PR?
I have on my to-do list to reshape the adding plugin to platform as well, not just project!

2022-02-14 10:51 UTC, ChasNelson1990 approved these changes

2022-02-14 10:55 UTC, joshuajames-smith requested changes
<img width="554" alt="Screenshot 2022-02-14 at 10 53 34" src="https://user-images.githubusercontent.com/83074763/153851020-28b6b2fa-50ce-4323-8d35-aa559589feb6.png">

Noticed this with the warning dialogue? I think this is the only thing that needs changed with this pr?

2022-02-14 11:34 UTC, joshuajames-smith approved these changes

2022-02-14 11:40 UTC, ChasNelson1990 approved these changes

2022-02-14 11:41 UTC, merged